# Generated by Django 5.1.4 on 2025-01-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150, unique=True)),
                ('dekan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('boshlanish_yili', models.PositiveIntegerField()),
                ('bitiruv_yili', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ismi', models.CharField(max_length=150)),
                ('mutaxassislik', models.CharField(max_length=150)),
                ('fakultet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oqituvchilar', to='students_app.fakultet')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familiyasi', models.CharField(max_length=100)),
                ('tugilgan_sana', models.DateField()),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talabalar', to='students_app.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='students_app.fakultet')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='students_app.yonalish'),
        ),
    ]
